stages:
  - "build"

build:
  stage: build
  image: docker:latest
  services:
    - "docker:dind"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build --target build -t $CI_REGISTRY_IMAGE:build .
    - docker build --target app -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE:build
    - docker push $CI_REGISTRY_IMAGE
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  tags:
    - "docker"
