services:
  fedistats-collector:
    image: "registry.gitlab.com/lig/fedistats:latest"
    volumes:
      - "./config/fedistats.yaml:/config/fedistats.yaml:ro"
  prometheus:
    image: prom/prometheus
    volumes:
      - "./config/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "9090:9090"
